#!/bin/bash

cargo fmt -- --check
# cargo clippy --workspace --all-targets --all-features -- --deny warnings

exit_code=$?

if [ $exit_code == "1" ]; then
  echo "There was a problem formatting, to fix run \`cargo fmt\`"
  exit 1
fi
